CBL-160: fix: error with JNI files and gradle in windows (#127)
* fix: "error C7555: use of designated initializers requires at least '/std:c++latest'"
* suppress: Exception might ignore
* fix: library path corrected for windows
* fix: incompatible visual cpp commands.
* fix: include header which are necessary.